import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'transitEvent',
  title: 'Sky Event',
  type: 'document',
  description: 'A specific moment when a planet moves, changes direction, or meets another planet. These are the raw signals that posts and timing reports are built from.',
  fields: [
    defineField({
      name: 'title',
      title: 'Event Name',
      type: 'string',
      description: 'Plain-English name for this sky event. e.g. "Mars enters Capricorn" or "Jupiter-Saturn Conjunction"',
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'planet',
      title: 'Planet',
      type: 'string',
      description: 'The primary planet involved.',
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'secondPlanet',
      title: 'Second Planet',
      type: 'string',
      description: 'For events involving two planets (conjunctions, oppositions, squares, trines).',
    }),
    defineField({
      name: 'eventType',
      title: 'Event Type',
      type: 'string',
      description: 'What kind of sky event is this?',
      options: {
        list: [
          { title: 'Ingress — Planet moves into a new sign', value: 'Ingress' },
          { title: 'Station Retrograde — Planet appears to reverse direction', value: 'Station Retrograde' },
          { title: 'Station Direct — Planet resumes forward motion', value: 'Station Direct' },
          { title: 'Conjunction — Two planets occupy the same degree', value: 'Conjunction' },
          { title: 'Opposition — Two planets face each other across the sky', value: 'Opposition' },
          { title: 'Square — Two planets at 90° tension angle', value: 'Square' },
          { title: 'Trine — Two planets at 120° harmonious angle', value: 'Trine' },
          { title: 'Eclipse — Solar or Lunar eclipse', value: 'Eclipse' },
          { title: 'Lunation — New or Full Moon', value: 'Lunation' },
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'date',
      title: 'Event Date & Time',
      type: 'datetime',
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'sign',
      title: 'Zodiac Sign',
      type: 'string',
      description: 'Which sign is the planet in at this event?',
    }),
    defineField({
      name: 'degree',
      title: 'Exact Degree',
      type: 'string',
      description: "Where in the sign, precisely. e.g. 8°15'",
    }),
    defineField({
      name: 'nakshatra',
      title: 'Lunar Mansion',
      type: 'string',
      description: 'The lunar mansion (nakshatra) the planet occupies — a finer slice of the sky than the zodiac sign.',
    }),
    defineField({
      name: 'subLord',
      title: 'Sub-Influence (KP Sub-Lord)',
      type: 'string',
      description: 'The planetary sub-ruler within the lunar mansion. Precision timing layer.',
    }),
    defineField({
      name: 'ayanamsa',
      title: 'Sky Calculation System',
      type: 'string',
      description: 'Correction system used. Default: Lahiri.',
      initialValue: 'Lahiri',
    }),
    defineField({
      name: 'significance',
      title: 'What This Means',
      type: 'text',
      rows: 4,
      description: 'Plain-English interpretation of this event and what it tends to surface in the world. Written by Travone or generated by agent.',
    }),
    defineField({
      name: 'fixedStars',
      title: 'Nearby Fixed Stars',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Fixed stars that fall close to this degree, which can amplify or color the event’s meaning. e.g. Antares, Algol, Spica',
    }),
    defineField({
      name: 'source',
      title: 'Calculation Source',
      type: 'string',
      description: 'Always Levite astro-calc-api. Do not change.',
      initialValue: 'Levite astro-calc-api',
    }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'date', planet: 'planet' },
    prepare({ title, subtitle, planet }) {
      return {
        title: `${planet ? planet + ' — ' : ''}${title}`,
        subtitle: subtitle ? new Date(subtitle).toLocaleDateString() : '',
      };
    },
  },
});
